//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleRenting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Driver()
        {
            this.Issues = new HashSet<Issue>();
            this.Notices = new HashSet<Notice>();
            this.HiredVehicles = new HashSet<HiredVehicle>();
            this.vehiclerequests = new HashSet<vehiclerequest>();
        }
    
        public int SalutationId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> RentDueDate { get; set; }
        public Nullable<System.DateTime> RentDate { get; set; }
        public Nullable<System.DateTime> ContractFrom { get; set; }
        public Nullable<System.DateTime> ContractTo { get; set; }
        public Nullable<int> ContractLength { get; set; }
        public Nullable<int> SourceId { get; set; }
        public string UserId { get; set; }
        public Nullable<decimal> SecurityDepositAmount { get; set; }
        public Nullable<decimal> AdvancedRentAmount { get; set; }
        public Nullable<decimal> HoldingDepositAmount { get; set; }
        public Nullable<decimal> AdminFee { get; set; }
        public Nullable<int> ReferenceId { get; set; }
        public string ReferenceDocumentPath { get; set; }
        public Nullable<int> IdentityId { get; set; }
        public string IdentityDocuementPath { get; set; }
        public Nullable<int> NationalityId { get; set; }
        public string SpecialConditions { get; set; }
        public int Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Issue> Issues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notice> Notices { get; set; }
        public virtual IdentityType IdentityType { get; set; }
        public virtual Nationality Nationality { get; set; }
        public virtual ReferenceType ReferenceType { get; set; }
        public virtual Salutation Salutation { get; set; }
        public virtual SourceType SourceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HiredVehicle> HiredVehicles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vehiclerequest> vehiclerequests { get; set; }
    }
}
