//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleRenting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HiredVehicle
    {
        public int id { get; set; }
        public int DriverId { get; set; }
        public int VehicleId { get; set; }
        public System.DateTime HireStartDate { get; set; }
        public Nullable<System.DateTime> HireEndDate { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
