//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleRenting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class noticereply
    {
        public int id { get; set; }
        public string reply { get; set; }
        public System.DateTime replydate { get; set; }
        public int noticeid { get; set; }
    
        public virtual Notice Notice { get; set; }
    }
}
