//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleRenting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.Contracts = new HashSet<Contract>();
        }
    
        public int Id { get; set; }
        public string RegistrationNo { get; set; }
        public string VehicleColor { get; set; }
        public bool AvailableToDouble { get; set; }
        public decimal RentPerWeek { get; set; }
        public int VehicleConditionId { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> AvailableDate { get; set; }
        public Nullable<bool> UnderOffer { get; set; }
        public int ProprietorId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract> Contracts { get; set; }
        public virtual proprietor proprietor { get; set; }
        public virtual VehicleCondition VehicleCondition { get; set; }
    }
}
